spring.application.name=what_to_eat

#log
logging.level.root=info

# monitoring
management.server.port=${ACTUATOR_PORT:9090}
management.endpoints.web.exposure.include=${ACTUATOR_EXPOSURE_ENDPOINT:health,prometheus,info}
management.endpoint.prometheus.access=read-only
management.endpoint.info.access=read-only
management.endpoint.health.access=read-only
management.prometheus.metrics.export.enabled=true

# Database
spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:what_to_eat}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:1111}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false
