pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-robot
  nodeSelector:
    kubernetes.io/hostname: k8s-worker-3
  containers:
  - name: buildah
    image: quay.io/buildah/stable
    command: ['sleep', 'infinity']
    securityContext:
      privileged: true
    volumeMounts:
    - name: storage
      mountPath: /var/lib/containers/storage
    - name: gradle-cache
      mountPath: /gradle-cache
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ['sleep', 'infinity']    
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: buildah-pvc
  - name: gradle-cache
    persistentVolumeClaim:
      claimName: gradle-pvc
"""
        }
    }

    options {
        buildDiscarder(logRotator(
            numToKeepStr: '10',
            artifactNumToKeepStr: '3'
        ))
    }

    environment {
        GHCR_REGISTRY = 'ghcr.io'
        GITHUB_USER = 'mungsil'
        IMAGE_NAME = 'what-to-eat'
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                    credentialsId: 'github-credentials',
                    url: 'https://github.com/mungsil/what_to_eat.git'
            }
        }

        stage('Build and Push Image') {
            steps {
                container('buildah') {
                    withCredentials([usernamePassword(
                        credentialsId: 'github-credentials',
                        usernameVariable: 'GHCR_USER',
                        passwordVariable: 'GHCR_TOKEN'
                    )]) {
                        sh '''
                            buildah login $GHCR_REGISTRY -u $GHCR_USER -p $GHCR_TOKEN
                            buildah bud -t $GHCR_REGISTRY/$GHCR_USER/$IMAGE_NAME:$IMAGE_TAG .
                            buildah push $GHCR_REGISTRY/$GHCR_USER/$IMAGE_NAME:$IMAGE_TAG
                            buildah rmi $GHCR_REGISTRY/$GHCR_USER/$IMAGE_NAME:$IMAGE_TAG
                        '''
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                container('kubectl') {
                    withKubeConfig([]) {
                        sh '''
                            kubectl set image deployment/whatToEat-spring-boot \
                                whatToEat-spring-boot=$GHCR_REGISTRY/$GITHUB_USER/$IMAGE_NAME:$IMAGE_TAG
                            kubectl rollout status deployment/whatToEat-spring-boot
                        '''
                    }
                }
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed'
        }
        success {
            echo 'Pipeline successfully completed'
        }
    }
}